### PR TITLE
Update config, round it out better. Also update my preset.

### PR DESCRIPTION
**Pull request by thedocruby**

### CODE REVIEW

**Comment by vlad2305m** [comment]
Sorry, the file you gave me earlier does not match these changes

**Comment by thedocruby** [comment]
@vlad2305m Sorry, fixed. I uploaded the wrong file.

**Comment by thedocruby** [comment]
@vlad2305m Also i apparently had a typo in the PR before, I got two settings mixed up. Fixed now. Sorry for the confusion, I hope it's not worth keeping the PR closed.

**Comment by thedocruby** [comment]
Superseded by #18

**Pull request closed without merging**
