### PR TITLE
Update config comments, preset

### PR DESCRIPTION
**Pull request by thedocruby**
I fixed the previous problems, sorry about the confusion.

### CODE REVIEW

**Comment by thedocruby** [comment]
This is a more tidy version of #15

**Comment by thedocruby** [comment]
You might notice the abundance of `1.0` in my new config, turns out that after extensive playtesting the mathematically correct values actually sound the most realistic, imagine that lol.

**Comment by vlad2305m** [comment]
Thank you very much for all the work you do for this project!

**Comment by vlad2305m** [comment]
If you plan to work on this further, I can grant you editting rights to GitHub and CurseForge

**Comment by thedocruby** [comment]
@vlad2305m That sounds like a good idea, I plan to submit a PR for the humidity absorption soon, having edit rights would make that much easier. And I'm happy to help, I enjoy supporting this mod as a Fabric alternative to forge mods such as Dynamic Surroundings.

(I know that Dynamic Surroundings has a fabric version, but its hard to deny that unlike sound physics fabric, it is a characteristic forge mod, having all the features without devoting development to any one feature. that's what makes mods like sodium, iris, okzoomer, lambdynamiclights, etc. better than optifine, and also one of the many reasons that I support fabric over forge.)

**Pull request merged**
